In [2]:
import numpy as np

In [3]:
data_1 = [1,2,3]
data_2 = [11,21,31]

data_1 = np.array(data_1)
data_2 = np.array(data_2)

data_1 + data_2

array([12, 23, 34])

Broadcasting

In [5]:
dist = np.array([1, 2, 3]) # unit is mile
distInKm = dist * 1.6

distInKm

array([1.6, 3.2, 4.8])

Broadcasting and conditions

In [6]:
data = [-1, 2, -4, 0, 3, 100, -5]

data = np.array(data)

data[data > 0]

array([  2,   3, 100])

In [8]:
#odd numbers

data = [-1, 2, -4, 0, 3, 100, -5]
data = np.array(data)

data[data%2 != 0]

array([-1,  3, -5])

Statistical Calculations

In [9]:
data = np.array([23, 2, 9, 8, 54, 89, 23])

data.sum()

208

In [11]:
data.min(), data.max(), data.mean(), data.std()

(2, 89, 29.714285714285715, 28.941884062051393)

Matrix

In [12]:
m = [[1, 2], [3, 4], [5, 6], [7, 8] ]
m = np.array(m)
m

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
m[0]

array([1, 2])

In [14]:
m[:,1]

array([2, 4, 6, 8])

In [15]:
m[1,:]

array([3, 4])